sudo: false
language: erlang
install:
  - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3
otp_release:
  - 19.3
script: "./rebar3 as test do dialyzer,ct,cover"
branches:
  only:
    - master